- name: Update and upgrade APY packages 
  apt: 
    update_cache: yes 
    upgrade: yes 

- name: Install devtools packages 
  apt: 
    name: "{{ devtools_packages }}" 
    state: present

- name: Set git global user name 
  become: no 
  git_config: 
    name: user.name 
    scope: global 
    value: "{{ git_global_username }}" 

- name: Set git global email 
  become: no 
  git_config: 
    name: user.email 
    scope: global 
    value: "{{ git_global_email }}" 

- name: Set git default branch
  become: no
  git_config: 
    name: init.defaultbranch
    scope: global 
    value: "{{ git_default_branch }}" 

- name: Set git default editor
  become: no
  git_config: 
    name: core.editor
    scope: global 
    value: "{{ git_core_editor }}" 

- name: Install zsh 
  apt: 
    name: zsh 
    state: present 
    update_cache: yes

- name: Ensure zsh binary is present 
  stat: 
    path: /usr/bin/zsh 
  register: zsh_bin

- name: Fail if zsh did not install correctly 
  fail: 
    msg: "Zsh installation failed (/usr/bin/zsh missing)." 
  when: not zsh_bin.stat.exists 

- name: Change default shell to zsh 
  user: 
    name: "{{ username }}" 
    shell: /usr/bin/zsh 

- name: Clone Oh My Zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "/home/{{ username }}/.oh-my-zsh"
    version: master
    depth: 1
    update: no
  become: no

- name: Ensure Zsh plugin directory exists
  file:
    path: "/home/{{ username }}/.oh-my-zsh/custom/plugins"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  become: no

- name: Clone zsh-suggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "/home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    version: master
    depth: 1
    update: no
  become: no

- name: Clone zsh-syntax-highlighting plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    version: master
    depth: 1
    update: no
  become: no

- name: Deploy .zshrc for Oh My Zsh with plugins
  template:
    src: zshrc.j2
    dest: "/home/{{ username }}/.zshrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  become: no

