- name: Remove legacy Docker packages
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    purge: yes

- name: Install apt HTTPS prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Create Docker keyring directory
  file:
    path: "{{ docker_keyring_dir }}"
    state: directory
    mode: '0755'

- name: Download Docker GPG key into keyrings 
  get_url: 
    url: "{{ docker_gpg_key_url }}"
    dest: /etc/apt/keyrings/docker.asc 
    owner: root 
    group: root 
    mode: '0644' 

- name: Add Docker apt repository
  apt_repository:
    filename: docker
    repo: "deb [arch=amd64 signed-by={{ docker_keyring_path }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name: "{{ docker_packages }}"
    state: present

- name: Add user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: Enable and start Docker service
  service:
    name: docker
    state: started
    enabled: yes

